erros = error1 + error2 + error3 + ...................... + error10

one error is loss.

cost functions

1. MAE
2. MSE
3. log loss

We use log loss for the logistric regression.

In [2]:
import numpy as np

In [21]:
y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [16]:
def mae(y_predicted, y_true):
    summ = 0
    for x,y in zip(y_predicted, y_true):
        summ = summ + abs(x-y)
    print("MAE")
    return summ/len(y_predicted)

In [17]:
mae(y_predicted, y_true)

MAE


0.5

In [22]:
np.mean(np.abs(y_predicted - y_true))                     #MAE

0.5

In [25]:
np.mean((y_predicted - y_true)**2)                       #MSE

0.366

In [33]:
np.log([10])

array([2.30258509])

In [38]:
np.log([0.00000000000001])

array([-32.2361913])

In [39]:
np.log([0.999999999999])

array([-9.99977878e-13])

In [54]:
y_predict = [abs((1e-15)-i) if i in [0,1] else i for i in y_predicted]
y_predict = np.array(y_predict)
y_predict

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [55]:
y_truth = [abs((1e-15)-i) if i in [0,1] else i for i in y_true]
y_truth = np.array(y_truth)
y_truth

array([3.e-01, 7.e-01, 1.e+00, 1.e-15, 5.e-01])

In [56]:
np.log(y_predict)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [58]:
-(np.mean( y_truth*np.log(y_predict) + (1-y_truth) * (np.log(1-y_predict)) ) )         # log loss

17.269628076684402